### ISSUE TITLE
issue#01 Añadir coordenada z en clase Point

### ISSUE THREAD

**Issue by GuillermoSanz** [GuillermoSanz/IWVG.SwC.GuillermoSanz#1]
Añadimos la coordenada 'z' de tipo entero en la clase Point. Se modificarán todos los métodos que lo requieran. Todos los constructores más los métodos y se añadirá el método getZ.
Actualizar los test Unitarios.

**Comment by borja94** [comment]
Hola Guillermo
Ya lo he hecho y subido.
Cierro la issue

**Comment by GuillermoSanz** [comment]
Hay smell code:
https://sonarcloud.io/project/issues?fileUuids=AV66U5U2mC7eQbpZbI9e&id=es.upm.miw%3AIWVG.SwC.GuillermoSanz&open=AV7EmdhYokkmKuhr78zv&resolved=false

Falta un espacio:
public Point(int xyz) {
        this(xyz, xyz,xyz);
}

Falta un espacio:
    public double module() {
         return Math.sqrt(this.x * this.x + this.y * this.y+ this.z * this.z);
}

Falta un espacio:
private int x, y,z;

**Comment by borja94** [comment]
corregido
