### ISSUE TITLE
issue#02 Nombre en formato latino. Nombre Apellido1 Apellido2.

### ISSUE THREAD

**Issue by GuillermoSanz** [GuillermoSanz/IWVG.SwC.GuillermoSanz#2]
Se agregará el método NombreLatino en la clase User que devuelva un string con el nombre seguido del primer y segundo apellidos, separados por un espacio entre ellos. Para ello se agregará el atributo secondFamilyName y el método get correspondiente.
Actualizar tests unitarios.

**Comment by MiguelArber** [comment]
Hecho, mergeado con Develop y subido a GitHub (tanto la rama de la issue como la nueva rama Develop).
