### ISSUE TITLE
issue#3 Lista con la parte entera de cada decimal.

### ISSUE THREAD

**Issue by GuillermoSanz** [GuillermoSanz/IWVG.SwC.GuillermoSanz#3]
Crear un método listaEntera que devuelva una lista de enteros a partir de un lista decimal.
Ejemplo: a partir de la lista de decimales[1.2 0.5 5.3] el resultado será la lista de enteros[1 0 5].
Actualizar tests unitarios

**Comment by egraciani** [comment]
Hecho en issue#3 y merge en develop

**Comment by GuillermoSanz** [comment]
No compila lo que has subido. El error está en el método de test de lista entera.
	    integerCollection = decimalCollection.listaEntera();
	    assertEquals(2, integerCollection.higher(),);
	    
Tienes que declarar integerCollection, y en la siguiente linea te sobra una coma.

**Comment by egraciani** [comment]
Hola Guillermo, acabo de corregirlo.

**Comment by GuillermoSanz** [comment]
Sigue sin compilar.

Creo que una solución podría ser está:

private ArrayList<Integer> integerCollection;

@Test
	public void testListaEntera() {
		this.integerCollection = this.decimalCollection.listaEntera();
		boolean result = 2 == integerCollection.get(0);
	    assert(result);
    }

**Comment by GuillermoSanz** [comment]
Fixed error
