### ISSUE TITLE
issue#4 añadir los métodos isPropia isImpropia en la clase Fraction

### ISSUE THREAD

**Issue by GuillermoSanz** [GuillermoSanz/IWVG.SwC.GuillermoSanz#4]
Incluir los métodos isPropia, isImpropia. Las fracciones propias son aquellas cuyo numerador es menor que el denominador, y las fracciones impropias el resto.
Actualizar los tests unitarios.

**Comment by borja94** [comment]
Ya está hecho

**Comment by GuillermoSanz** [comment]
great, te reabri un issue por unos espacio, el sonar es muy pesao
