### ISSUE TITLE
issue#05 añadir el método isEquivalente en la clase Fraction

### ISSUE THREAD

**Issue by GuillermoSanz** [GuillermoSanz/IWVG.SwC.GuillermoSanz#5]
Incluir el método isEquivalente en la clase Fraction. Dos fracciones son equivalentes cuando el producto de extremos es igual al producto de medios.
Actualizar tests unitarios.

**Comment by MiguelArber** [comment]
Hecho, mergeado con Develop y subido a GitHub (tanto la rama de la issue como la nueva rama Develop).
